spin_manifest_version = 2

[application]
name = "spin-o11y"
version = "0.1.0"
authors = ["thangchung <thangchung@ymail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-o11y"

[component.spin-o11y]
source = "target/wasm32-wasi/release/spin_o11y.wasm"
allowed_outbound_hosts = []
[component.spin-o11y.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
